# 텐서플로우 / Keras

In [2]:
import numpy as np 
import tensorflow as tf
import keras

In [ ]:
keras.__version__

'3.14.1'

In [6]:
keras.config.backend()

'tensorflow'

In [ ]:
# 0차원 스칼라 - 숫자 하나
scalar = tf.constant(3.1)

In [8]:
# 1차원 - 벡터 - 피처 1개의 샘플 or 샘플 1개의 피처값들
vector = tf.constant([1, 2, 3])

In [ ]:
# 2차원 - 행렬 - 표, 테이블
matrix = tf.constant([
    [1, 2, 3],
    [4, 5, 6]   
]) # (2, 3의 행렬)

matrix = tf.zeros((100, 3))  # (100, 3)의 0 행렬


TensorShape([100, 3])

In [13]:
# 3차원 - (샘플 수 * 높이 * 너비) - 이미지
tensor_3d = tf.zeros((300, 100, 100))
tensor_3d.shape

TensorShape([300, 100, 100])

In [15]:
# 차원 확인하기
tensor_3d.ndim

3

In [16]:
# tensor -> numpy
type(tensor_3d.numpy())

numpy.ndarray

In [39]:
# AI에게 텐서 연산 한번 줘봐
a = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)
b = tf.constant([[0.1, 0.2], [0.3, 0.4]], dtype=tf.float32)

c = tf.matmul(a, b)
print(c)

tf.Tensor(
[[0.70000005 1.        ]
 [1.5        2.2       ]], shape=(2, 2), dtype=float32)


# Keras : 고수준 API
- Sequential : 층을 순서대로 쌓겠다.
- Dense : 퍼셉트론 여러개를 하나의 층으로 묶은 연결층
- ...

1. 모델을 정의한다
2. 레이어 블록을 쌓는다.
3. 컴파일 한다.
4. 학습한다.
5. 평가한다.

In [45]:
x = np.array([ [1.0, 0.0] ]) # 입력 값, 샘플 1개, 특성 2개

print(x.shape)  # (1, 2)

dense = keras.layers.Dense(units=1,   # 해당 층의 뉴런 갯수(출력 노드) 1개
                           activation="sigmoid",
                           input_shape=(2,) # 입력되는 특성 수가 2개
                           )  # 층 1개 생성

(1, 2)


In [ ]:
y = dense(x)  # 층에 입력값을 넣음.

In [32]:
w, b = dense.get_weights() # w, b를 반환한다.

In [34]:
print(w.shape, x.shape)
# x shape은
# 배치 크기, 특성 개수  [ [1.0, 0.0] ]
# w shape은
# (입력 특성의 개수, 출력 뉴런의 개수)

(2, 1) (1, 2)


In [46]:
print(b.shape)

(2, 2)


In [ ]:
# 행렬 곱셈을 하는 층을 만든 것
# 행렬 곱의 shape (1, 2) * (2, 1) = (1, 1)
# 행렬 곱의 shape (2, 1) * (1, 2) = (2, 2)
# Dense 가 하는 일 => 층에서 각 unit 행렬 곱

x @ w + b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8695865 , -0.76958656],
       [-0.66958654, -0.5695865 ]], dtype=float32)>

In [ ]:
## 입력 값이 특성이 3개고 뉴런도 3개인 Dense를 만들어보세요.

In [56]:
from keras import Sequential
from keras.layers import Input, Dense

# 모델을 만들기

model = Sequential([
    Input(shape=(4,)), # 입력층
    Dense(8, activation="sigmoid"),  # 은닉층
    Dense(3, activation="softmax")   # 출력층
    ])

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_19 (Dense)                │ (None, 8)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 3)              │            27 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 67 (268.00 B)

 Trainable params: 67 (268.00 B)

 Non-trainable params: 0 (0.00 B)

## 머신러닝과 비교

In [66]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_digits

digits = load_digits()
X = digits.data / 16.0   # 정규화
y = digits.target

X_tr, X_val, y_tr, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)
lr = LogisticRegression(max_iter=2000)
lr.fit(X_tr, y_tr)
print(lr.score(X_val, y_val))   # 0.9667

0.9666666666666667


In [60]:
digits.data.shape

(1797, 64)

In [ ]:
import keras
keras.utils.set_random_seed(42)

model = keras.Sequential([
    keras.layers.Input(shape=(64,)),
    keras.layers.Dense(10, activation='softmax')
])
# 학습 방식 설정
model.compile(loss='sparse_categorical_crossentropy', # 손실함수 : 크로스엔트로피
              metrics=['accuracy'])   # 평가 지표 : 정확도
model.fit(X_tr, y_tr, epochs=30,  # 학습용 데이터 넣어서 학습, 30번 반복 학습
          validation_data=(X_val, y_val), verbose=0)  # validation

_, acc = model.evaluate(X_val, y_val, verbose=0)  # 정확도 확인. 검증 데이터로.
print(acc)   # 유사한 수준

0.925000011920929


In [67]:
(train_input, train_target), _ = \
    keras.datasets.fashion_mnist.load_data()

print(train_input.shape)   # (60000, 28, 28)
print(train_input.dtype)   # uint8
print(train_input.min(), train_input.max())
# 0  255

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
(60000, 28, 28)
uint8
0 255
